"""TAGS code mapping for ACP-127 messages.

Subject TAGS (PERMANENT_SUBJECT_TAGS, TEMPORARY_SUBJECT_TAGS) come from
docs/faqs.txt, Appendix I and Appendix II (National Archives RG 59 CFPF FAQ)
-- this is the authoritative, official source, and every code in these two
dicts plus the E/M/P/S/T wildcard rule is FAQ-documented.

ORGANIZATION_TAGS is a separate, non-FAQ mapping, built from two primary
sources plus one research-based source, in priority order:
  1. The period-accurate 1974 State Dept handbook (docs/rg59_state_dept_tags_74.pdf,
     Section 15 "List of Organization TAGS", TL:TAGS-1, 6-28-74) -- the
     PRESCRIBED list of Organization TAGS actually valid during this corpus's
     1973-1979 date range. Transcribed directly from page images (the OCR
     text layer for this scan is too corrupted to trust).
  2. For codes not in that handbook: corpus text evidence (spelled out in
     sampled real documents, or an unambiguous standard institution) -- see
     docs/tags_coverage.md for that methodology and citations.
Ambiguous/unconfirmed guesses from either source are excluded entirely.

COUNTRY_TAGS_1974 and REGION_TAGS_1974 are the PRIMARY geographic mapping --
same 1974 handbook, Section 11 "List of Geographic TAGS Alphabetically by
Country or World Regions" -- period-accurate for this corpus. Transcribed
directly from page images for the same OCR-quality reason as above.

COUNTRY_TAGS and REGION_TAGS are a SECONDARY/fallback mapping from the State
Department's *current* TAGS reference (5 FAH-3 H-414 / H-416,
https://fam.state.gov/FAM/05FAH03/05FAH030410.html) -- authoritative, but for
today's (2024) code system, which was recoded onto GENC/ISO-3166 at some
point after 1979. Many codes actually used in this corpus are legacy codes
that differ from today's (e.g. old "UK" vs modern "GB", old "IZ" vs modern
"IQ") or refer to entities that no longer exist (USSR "UR", Yugoslavia "YO",
South Vietnam "VS", ...), so the 1974 handbook resolves
far more of this corpus (94.8% of geographic-shaped occurrences measured on
1973 data) than the modern table alone (66.8%). lookup_geographic_tag()
checks the 1974 dicts first and falls back to the modern ones only for codes
the 1974 handbook doesn't cover (e.g. countries that gained independence
after its June 1974 print date, like Angola or Mozambique).

Do not add legacy-era guesses to any of these dicts without the same
primary-source-or-confirmed-evidence rigor used to build them.
"""

PERMANENT_SUBJECT_TAGS = {
    "ACLM": ("Administration", "Claims Against the U.S. Government"),
    "ACMM": ("Administration", "Committees"),
    "AEMR": ("Administration", "Emergency Planning and Evacuation"),
    "AGAO": ("Administration", "General Accounting Office"),
    "AINF": ("Administration", "Information Management Services"),
    "AINR": ("Administration", "INR Program Administration"),
    "ALTR": ("Administration", "Newsletter"),
    "AMGT": ("Administration", "Management Operations"),
    "AODE": ("Administration", "Employees Abroad"),
    "AORG": ("Administration", "International Organization Administration"),
    "ASEC": ("Administration", "Security"),
    "ASIG": ("Administration", "Inspector General Activities"),
    "BAGB": ("Business Services", "Agribusiness"),
    "BBAK": ("Business Services", "Background on Firms, Products, and Individuals"),
    "BBCP": ("Business Services", "Business Consultation Program"),
    "BBSR": ("Business Services", "Business Services Reporting"),
    "BDIS": ("Business Services", "Trade Complaints and Disputes"),
    "BENC": ("Business Services", "Engineering and Construction Services"),
    "BEXP": ("Business Services", "Trade Expansion and Promotion"),
    "BFOL": ("Business Services", "Follow-up Request"),
    "BGEN": ("Business Services", "Business Services - General"),
    "BPRO": ("Business Services", "Business Proposals and Inquiries"),
    "BTIO": ("Business Services", "Trade and Investment Opportunities"),
    "BTRA": ("Business Services", "Travel by U.S. and Foreign Businessmen"),
    "CARR": ("Consular Affairs", "Americans Arrested Abroad"),
    "CASC": ("Consular Affairs", "Assistance to Citizens"),
    "CDES": ("Consular Affairs", "Deaths and Estates"),
    "CFED": ("Consular Affairs", "Federal Agency Services"),
    "CGEN": ("Consular Affairs", "Consular Affairs - General"),
    "CPRS": ("Consular Affairs", "Property Protection Services"),
    "OCLR": ("Operations", "Military Vessel and Flight Clearances and Visits"),
    "OCON": ("Operations", "Conferences and Meetings"),
    "OGEN": ("Operations", "Operations - General"),
    "OREP": ("Operations", "U.S. Congressional Travel"),
    "OVIP": ("Operations", "Visits and Travel of Prominent Individuals and Leaders"),
}

TEMPORARY_SUBJECT_TAGS = {
    "AART": ("Administration", "Art-in-Embassies Program"),
    "AAUD": ("Administration", "Audits"),
    "ABLD": ("Administration", "Buildings"),
    "ABUD": ("Administration", "Budget Services and Financial Systems"),
    "ACOM": ("Administration", "Departmental Communications"),
    "ACMS": ("Administration", "COMSEC Material"),
    "ACOU": ("Administration", "Courier Operations"),
    "ADTO": ("Administration", "Domestic Telecommunications Operations"),
    "AFAC": ("Administration", "Commo & Records Unit/Combined Commo Centers (CRU/CCC)"),
    "AFIN": ("Administration", "Financial Services"),
    "AFOP": ("Administration", "Foreign Service Post COM Center Operations & Administration"),
    "AFSI": ("Administration", "Foreign Service Institute"),
    "AFSP": ("Administration", "Post Administration"),
    "ALIB": ("Administration", "Library Services"),
    "ALOW": ("Administration", "Allowances"),
    "AMED": ("Administration", "Medical Services"),
    "AMTC": ("Administration", "Telecommunications Equipment Maintenance"),
    "ANET": ("Administration", "Communications, circuits, and Networks"),
    "APER": ("Administration", "Personnel"),
    "APOU": ("Administration", "Mail and Pouch"),
    "APUB": ("Administration", "Publishing, Printing, Distribution, and Library Services"),
    "AREC": ("Administration", "Commissary and Recreation"),
    "AREG": ("Administration", "Regulations and Directives"),
    "ASAF": ("Administration", "Safety"),
    "ASCH": ("Administration", "Overseas Schools"),
    "ASUP": ("Administration", "Supplies and Equipment"),
    "ATRN": ("Administration", "Transportation"),
    "AVCE": ("Administration", "Foreign Service Post Voice Communications Facility"),
    "AWRD": ("Administration", "Awards"),
    "BLIB": ("Business Services", "Commercial Libraries"),
    "BPUB": ("Business Services", "Business-Commercial Publications and Libraries"),
    "CPAS": ("Consular Affairs", "Passports and Citizenship"),
    "CVIS": ("Consular Affairs", "Visas"),
    "OEXC": ("Operations", "Educational and Cultural Exchange Operations"),
    "OSCI": ("Operations", "Science Grants"),
    "OTRA": ("Operations", "Travel and Visits"),
}

# Organization TAGS meanings (NOT from docs/faqs.txt -- the FAQ does not
# define Organization TAGS at all). Two provenances, each labeled inline
# below: the period-accurate 1974 State Dept handbook (primary source), and
# codes it doesn't cover, confirmed instead via corpus text evidence -- see
# docs/tags_coverage.md for the latter's full methodology.
ORGANIZATION_TAGS = {
    # --- Confirmed via 5 FAH-3 (State Dept RG59) "TRAFFIC ANALYSIS BY GEOGRAPHY
    # AND SUBJECT" handbook, TL:TAGS-1, 6-28-74 (docs/rg59_state_dept_tags_74.pdf,
    # Section 15 "List of Organization TAGS") -- the period-accurate PRIMARY SOURCE,
    # transcribed directly from page images (OCR of this scan is too poor to trust).
    "ADB": "Asian Development Bank",
    "AEC": "Atomic Energy Commission",
    "AFDB": "African Development Bank",
    "AIFLD": "American Institute for Free Labor Development",
    "ANZUS": "Australia, New Zealand, and United States Council",
    "ASEAN": "Association of South East Asian Nations",
    "BIE": "Bureau of International Exhibitions",
    "C-20": "Committee of 20 for International Monetary Reform (IMF)",
    "CAB": "Civil Aviation Board",
    "CCD": "Conference of the Committee on Disarmament",
    "CCMS": "Committee on the Challenges of Modern Society (NATO)",
    "CENTO": "Central Treaty Organization",
    "COCOM": "Coordinating Committee on Export Controls",
    "COE": "Council of Europe",
    "COMECON": "Council for Mutual Economic Assistance",
    "CSCE": "Conference on Security and Cooperation in Europe",
    "DAC": "Development Assistance Committee (OECD)",
    "DEA": "Drug Enforcement Agency",
    "DPC": "Defense Planning Committee (NATO)",
    "ECA": "UN Economic Commission for Africa",
    "ECAC": "European Committee on Civil Aviation",
    "ECAFE": "UN Economic Commission for Asia and the Far East",
    "ECE": "UN Economic Commission for Europe",
    "ECLA": "UN Economic Commission for Latin America",
    "ECOSOC": "UN Economic and Social Council",
    "ECWA": "Economic Commission for Western Asia",
    "EEC": "European Common Market (European Communities)",
    "EFTA": "European Free Trade Association",
    "EPA": "Environmental Protection Agency",
    "FAO": "Food and Agriculture Organization (UN)",
    "G-10": "Group of Ten",
    "GATT": "General Agreement on Tariffs and Trade",
    "IA-ECOSOC": "Inter-American Economic and Social Council (not a part of UN ECOSOC)",
    "IAEA": "International Atomic Energy Agency",
    "IARC": "International Agency for Research on Cancer",
    "IATA": "International Air Transport Association",
    "IATTC": "Inter-American Tropical Tuna Commission",
    "IBRD": "International Bank for Reconstruction and Development",
    "ICAO": "International Civil Aviation Organization",
    "ICEM": "Intergovernmental Committee for European Migration",
    "ICFTU": "International Confederation of Free Trade Unions",
    "ICJ": "International Court of Justice",
    "ICJU": "International Commission of Jurists",
    "ICNAF": "International Commission for the Northwest Atlantic Fisheries",
    "ICRC": "International Committee of the Red Cross",
    "IDB": "Inter-American Development Bank",
    "ILC": "International Law Commission",
    "ILO": "International Labor Organization",
    "IMCO": "Intergovernmental Maritime Consultative Organization",
    "IMF": "International Monetary Fund",
    "INTELSAT": "International Telecommunications Satellite Consortium",
    "ISVS": "International Secretariat for Volunteer Services",
    "ITU": "International Telecommunications Union",
    "JCC": "Joint Commercial Commissions",
    "LAFTA": "Latin American Free Trade Association",
    "MARAD": "U.S. Maritime Administration",
    "MBFR": "Mutual and Balanced Force Reduction Talks",
    "NAC": "North Atlantic Council (NATO)",
    "NASA": "National Aeronautics and Space Council",
    "NATO": "North Atlantic Treaty Organization",
    "NOAA": "National Oceanographic and Atmospheric Agency",
    "NPG": "Nuclear Planning Group (NATO)",
    "NSF": "National Science Foundation",
    "OAPEC": "Organization of Arab Petroleum Exporting Countries",
    "OAS": "Organization of American States",
    "OAU": "Organization of African Unity",
    "OECD": "Organization for Economic Cooperation and Development",
    "OPEC": "Organization of Petroleum Exporting Countries",
    "OPIC": "Overseas Private Investment Corporation",
    "PAHO": "Pan American Health Organization",
    "PLO": "Palestine Liberation Organization",
    "SEATO": "Southeast Asia Treaty Organization",
    "SPC": "South Pacific Commission",
    "UN": "United Nations",
    "UNCND": "UN Commission on Narcotic Drugs",
    "UNCSW": "UN Commission on Status of Women",
    "UNCTAD": "UN Conference on Trade and Development",
    "UNDP": "UN Development Program",
    "UNEP": "UN Environmental Program",
    "UNESCO": "UN Educational, Scientific and Cultural Organization",
    "UNFDAC": "UN Fund for Drug Abuse Control",
    "UNFPA": "UN Fund for Population Activities",
    "UNGA": "UN General Assembly",
    "UNHCR": "UN High Commissioner for Refugees",
    "UNHRC": "UN Human Rights Commission",
    "UNICEF": "UN Children's Fund",
    "UNIDO": "UN Industrial Development Organization",
    "UNITAR": "UN Institute for Training and Research",
    "UNPOC": "UN Population Commission",
    "UNRWA": "UN Relief and Works Agency for Palestine Refugees",
    "UNSC": "UN Security Council",
    "UNSDC": "UN Social Development Commission",
    "UNSTC": "UN Statistical Commission",
    "UNTC": "UN Trusteeship Council",
    "UNV": "UN Volunteers",
    "UPU": "Universal Postal Union",
    "USTS": "U.S. Travel Service",
    "WHO": "World Health Organization",
    "WIPO": "World Intellectual Property Organization",
    "WMO": "World Meteorological Organization",
    "WTO": "Warsaw Pact Organization",
    "XMB": "Export-Import Bank of the United States",

    # --- Confirmed via corpus text evidence (docs/tags_coverage.md sampling
    # methodology) -- not in the 1974 handbook's prescribed list, but independently
    # spelled out or unambiguous in real sampled documents.
    "AALC": "African-American Labor Center",
    "ABCC": "Atomic Bomb Casualty Commission (Tokyo, US-Japan joint body)",
    "ACDA": "US Arms Control and Disarmament Agency",
    "AFDF": "African Development Fund",
    "AIIC": "American International Insurance Company (in this dataset's usage — not to be confused with the interpreters' association of the same acronym)",
    "ALIA": "Alia — The Royal Jordanian Airline",
    "APRA": "Alianza Popular Revolucionaria Americana (Peruvian political party)",
    "BWIA": "British West Indian Airways",
    "CACM": "Central American Common Market",
    "CCIR": "International Radio Consultative Committee",
    "CEAO": "Communauté Économique de l'Afrique de l'Ouest (West African Economic Community)",
    "CEMA": "Council for Mutual Economic Assistance (COMECON)",
    "CEPE": "Corporación Estatal Petrolera Ecuatoriana (Ecuador state oil company)",
    "CGIL": "Confederazione Generale Italiana del Lavoro (Italian communist-aligned union federation)",
    "CIEC": "Conference on International Economic Cooperation (\"North-South Dialogue\")",
    "CIME": "OECD Committee on International Investment and Multinational Enterprises",
    "CISL": "Confederazione Italiana Sindacati Lavoratori (Italian trade union confederation)",
    "CNAD": "NATO Conference of National Armaments Directors",
    "CNEA": "Comisión Nacional de Energía Atómica (Argentina's atomic energy commission)",
    "CPSU": "Communist Party of the Soviet Union",
    "CSTP": "OECD Committee for Scientific and Technological Policy",
    "FARC": "Fuerzas Armadas Revolucionarias de Colombia",
    "FCIA": "Foreign Credit Insurance Association",
    "FEOF": "Foreign Exchange Operations Fund (Laos monetary stabilization fund)",
    "FHWA": "Federal Highway Administration",
    "FIAT": "Fabbrica Italiana Automobili Torino (Italian automaker)",
    "FLEC": "Frente de Libertação do Enclave de Cabinda",
    "FNCB": "First National City Bank (Citibank's former name)",
    "FNLA": "Frente Nacional de Libertação de Angola",
    "FSLN": "Frente Sandinista de Liberación Nacional (Sandinista National Liberation Front, Nicaragua)",
    "IAJC": "Inter-American Juridical Committee",
    "ICAC": "International Cotton Advisory Committee",
    "ICAF": "Industrial College of the Armed Forces",
    "ICCO": "International Cocoa Organization",
    "ICCS": "International Commission of Control and Supervision (Vietnam ceasefire body)",
    "ICES": "International Council for the Exploration of the Sea",
    "IESC": "International Executive Service Corps",
    "IFAD": "International Fund for Agricultural Development",
    "IFRB": "International Frequency Registration Board (ITU)",
    "IGGI": "Inter-Governmental Group on Indonesia (aid consortium)",
    "INCB": "International Narcotics Control Board",
    "IRSG": "International Rubber Study Group",
    "KCIA": "Korean Central Intelligence Agency",
    "LPDR": "Lao People's Democratic Republic (official name post-1975)",
    "NACB": "Non-Aligned Coordinating Bureau",
    "NACC": "Non-Aligned Coordinating Committee",
    "NIOC": "National Iranian Oil Company",
    "NMFS": "National Marine Fisheries Service",
    "NTSB": "National Transportation Safety Board",
    "OCAM": "Organisation Commune Africaine et Malgache",
    "ORIT": "Inter-American Regional Organization of Workers (AFL-CIO-affiliated)",
    "PANAM": "Pan American World Airways",
    "QUAI": "Quai d'Orsay (metonym for the French Foreign Ministry)",
    "UJNR": "US-Japan Cooperative Program in Natural Resources",
    "UNEF": "UN Emergency Force",
    "USAF": "US Air Force",
    "USDA": "US Department of Agriculture",
    "USGS": "US Geological Survey",
    "USIA": "United States Information Agency",
    "USIS": "US Information Service (overseas arm of USIA)",
    "WARC": "World Administrative Radio Conference",
    "WFTU": "World Federation of Trade Unions",
    "ZANU": "Zimbabwe African National Union",
    "ZAPU": "Zimbabwe African People's Union",
}

# Source: 5 FAH-3 H-414, "COUNTRY TAGS ORDERED BY TAGS"
# https://fam.state.gov/FAM/05FAH03/05FAH030410.html (CT:TAGS-96; 03-04-2024)
# CURRENT (2024) codes only -- pre-1990s State Dept 2-letter codes used in this
# 1973-1979 corpus predate the GENC/ISO-3166 recoding and largely differ from
# today's codes (e.g. old "UK" vs modern "GB", old "JA" vs modern "JP", old
# "IZ" vs modern "IQ"), and dissolved entities (USSR "UR", Yugoslavia "YO",
# South Vietnam "VS", etc.) have no current code at all.
# Measured on 1973 data, this table alone resolves 66.8% of geographic-shaped
# TAGS occurrences -- see COUNTRY_TAGS_1974/REGION_TAGS_1974 below (the
# period-accurate 1974 handbook, which resolves 94.8%) for the primary
# lookup; this modern table is only the fallback -- see docs/tags_coverage.md.
COUNTRY_TAGS = {
    "AD": "Andorra",
    "AE": "United Arab Emirates",
    "AF": "Afghanistan",
    "AG": "Antigua and Barbuda",
    "AI": "Anguilla",
    "AL": "Albania",
    "AM": "Armenia",
    "AO": "Angola",
    "AQ": "Antarctica",
    "AR": "Argentina",
    "AS": "American Samoa",
    "AT": "Austria",
    "AU": "Australia",
    "AW": "Aruba",
    "AZ": "Azerbaijan",
    "BA": "Bosnia and Herzegovina",
    "BB": "Barbados",
    "BD": "Bangladesh",
    "BE": "Belgium",
    "BF": "Burkina Faso",
    "BG": "Bulgaria",
    "BH": "Bahrain",
    "BI": "Burundi",
    "BJ": "Benin",
    "BL": "Saint Barthelemy",
    "BM": "Bermuda",
    "BN": "Brunei",
    "BO": "Bolivia",
    "BQ": "Bonaire, Sint Eustatius and Saba",
    "BR": "Brazil",
    "BS": "Bahamas, The",
    "BT": "Bhutan",
    "BV": "Bouvet Island",
    "BW": "Botswana",
    "BY": "Belarus",
    "BZ": "Belize",
    "CA": "Canada",
    "CC": "Cocos (Keeling) Islands",
    "CD": "Congo (Kinshasa)",
    "CF": "Central African Republic",
    "CG": "Congo (Brazzaville)",
    "CH": "Switzerland",
    "CI": "Cote d’Ivoire",
    "CK": "Cook Islands",
    "CL": "Chile",
    "CM": "Cameroon",
    "CN": "China",
    "CO": "Colombia",
    "CP": "Clipperton Island",
    "CR": "Costa Rica",
    "CU": "Cuba",
    "CV": "Cabo Verde",
    "CW": "Curaçao",
    "CX": "Christmas Island",
    "CY": "Cyprus",
    "CZ": "Czechia",
    "DE": "Germany",
    "DJ": "Djibouti",
    "DK": "Denmark",
    "DM": "Dominica",
    "DO": "Dominican Republic",
    "DZ": "Algeria",
    "EC": "Ecuador",
    "EE": "Estonia",
    "EG": "Egypt",
    "EH": "Western Sahara",
    "ER": "Eritrea",
    "ES": "Spain",
    "ET": "Ethiopia",
    "FI": "Finland",
    "FJ": "Fiji",
    "FK": "Falkland Islands (Islas Malvinas)",
    "FM": "Micronesia (Federated States of)",
    "FO": "Faroe Islands",
    "FR": "France",
    "GA": "Gabon",
    "GB": "United Kingdom",
    "GD": "Grenada",
    "GE": "Georgia",
    "GF": "French Guiana",
    "GG": "Guernsey",
    "GH": "Ghana",
    "GI": "Gibraltar",
    "GL": "Greenland",
    "GM": "Gambia (The)",
    "GN": "Guinea",
    "GP": "Guadeloupe",
    "GQ": "Equatorial Guinea",
    "GR": "Greece",
    "GS": "South Georgia and the South Sandwich Islands",
    "GT": "Guatemala",
    "GU": "Guam",
    "GW": "Guinea-Bissau",
    "GY": "Guyana",
    "HK": "Hong Kong",
    "HM": "Heard Island and McDonald Islands",
    "HN": "Honduras",
    "HR": "Croatia",
    "HT": "Haiti",
    "HU": "Hungary",
    "ID": "Indonesia",
    "IE": "Ireland",
    "IL": "Israel",
    "IM": "Isle of Man",
    "IN": "India",
    "IO": "British Indian Ocean Territory",
    "IQ": "Iraq",
    "IR": "Iran",
    "IS": "Iceland",
    "IT": "Italy",
    "JE": "Jersey",
    "JM": "Jamaica",
    "JO": "Jordan",
    "JP": "Japan",
    "KE": "Kenya",
    "KG": "Kyrgyzstan",
    "KH": "Cambodia",
    "KI": "Kiribati",
    "KM": "Comoros",
    "KN": "Saint Kitts and Nevis",
    "KP": "Korea (North)",
    "KR": "Korea (South)",
    "KW": "Kuwait",
    "KY": "Cayman Islands",
    "KZ": "Kazakhstan",
    "LA": "Laos",
    "LB": "Lebanon",
    "LC": "Saint Lucia",
    "LI": "Liechtenstein",
    "LK": "Sri Lanka",
    "LR": "Liberia",
    "LS": "Lesotho",
    "LT": "Lithuania",
    "LU": "Luxembourg",
    "LV": "Latvia",
    "LY": "Libya",
    "MA": "Morocco",
    "MC": "Monaco",
    "MD": "Moldova",
    "ME": "Montenegro",
    "MF": "Saint Martin",
    "MG": "Madagascar",
    "MH": "Marshall Islands",
    "MK": "Macedonia",
    "ML": "Mali",
    "MM": "Burma",
    "MN": "Mongolia",
    "MO": "Macau",
    "MP": "Northern Mariana Islands",
    "MQ": "Martinique",
    "MR": "Mauritania",
    "MS": "Montserrat",
    "MT": "Malta",
    "MU": "Mauritius",
    "MV": "Maldives",
    "MW": "Malawi",
    "MX": "Mexico",
    "MY": "Malaysia",
    "MZ": "Mozambique",
    "NA": "Namibia",
    "NC": "New Caledonia",
    "NE": "Niger",
    "NF": "Norfolk Island",
    "NG": "Nigeria",
    "NI": "Nicaragua",
    "NL": "Netherlands",
    "NO": "Norway",
    "NP": "Nepal",
    "NR": "Nauru",
    "NU": "Niue",
    "NZ": "New Zealand",
    "OM": "Oman",
    "PA": "Panama",
    "PE": "Peru",
    "PF": "French Polynesia",
    "PG": "Papua New Guinea",
    "PH": "Philippines",
    "PK": "Pakistan",
    "PL": "Poland",
    "PM": "Saint Pierre and Miquelon",
    "PN": "Pitcairn Islands",
    "PR": "Puerto Rico",
    "PT": "Portugal",
    "PW": "Palau",
    "PY": "Paraguay",
    "QA": "Qatar",
    "QM": "Midway Islands",
    "QS": "Bassas da India",
    "QU": "Juan de Nova Island",
    "QW": "Wake Island",
    "QX": "Glorioso Islands",
    "QZ": "Akrotiri",
    "RE": "Reunion",
    "RO": "Romania",
    "RS": "Serbia",
    "RU": "Russia",
    "RW": "Rwanda",
    "SA": "Saudi Arabia",
    "SB": "Solomon Islands",
    "SC": "Seychelles",
    "SD": "Sudan",
    "SE": "Sweden",
    "SG": "Singapore",
    "SH": "Saint Helena, Ascension, and Tristan da Cunha",
    "SI": "Slovenia",
    "SK": "Slovakia",
    "SL": "Sierra Leone",
    "SM": "San Marino",
    "SN": "Senegal",
    "SO": "Somalia",
    "SR": "Suriname",
    "SS": "South Sudan",
    "ST": "Sao Tome and Principe",
    "SV": "El Salvador",
    "SX": "Sint Maarten",
    "SY": "Syria",
    "SZ": "Swaziland",
    "TC": "Turks and Caicos Islands",
    "TD": "Chad",
    "TF": "French Southern and Antarctic Lands",
    "TG": "Togo",
    "TH": "Thailand",
    "TJ": "Tajikistan",
    "TK": "Tokelau",
    "TL": "Timor-Leste",
    "TM": "Turkmenistan",
    "TN": "Tunisia",
    "TO": "Tonga",
    "TR": "Turkey",
    "TT": "Trinidad and Tobago",
    "TV": "Tuvalu",
    "TW": "Taiwan",
    "TZ": "Tanzania",
    "UA": "Ukraine",
    "UG": "Uganda",
    "US": "United States",
    "UY": "Uruguay",
    "UZ": "Uzbekistan",
    "VA": "Vatican City",
    "VC": "Saint Vincent and the Grenadines",
    "VE": "Venezuela",
    "VG": "British Virgin Islands",
    "VI": "U.S. Virgin Islands",
    "VN": "Vietnam",
    "VU": "Vanuatu",
    "WF": "Wallis and Futuna",
    "WS": "Samoa",
    "XA": "Ashmore and Cartier Islands",
    "XB": "Baker Island",
    "XC": "Coral Sea Islands",
    "XD": "Dhekelia",
    "XE": "Europa Island",
    "XG": "Gaza Strip",
    "XH": "Howland Island",
    "XJ": "Jan Mayen",
    "XK": "Kosovo",
    "XL": "Palmyra Atoll",
    "XP": "Paracel Islands",
    "XQ": "Jarvis Island",
    "XR": "Svalbard",
    "XS": "Spratly Islands",
    "XT": "Tromelin Island",
    "XU": "Johnston Atoll",
    "XV": "Navassa Island",
    "XW": "West Bank",
    "YE": "Yemen",
    "YT": "Mayotte",
    "ZA": "South Africa",
    "ZM": "Zambia",
    "ZW": "Zimbabwe",
}

# Source: 5 FAH-3 H-416, "WORLD REGION TAGS ORDERED BY TAGS" (same page/caveat as above)
REGION_TAGS = {
    "1A": "Africa",
    "1C": "Central Africa",
    "1E": "East Africa",
    "1N": "North Africa",
    "1S": "Southern Africa",
    "1W": "West Africa",
    "2A": "Arabian Peninsula",
    "2C": "Central Asia",
    "2E": "East Asia",
    "2H": "Southeast Asia",
    "2M": "Middle East",
    "2N": "North Asia",
    "2P": "East Asia and Pacific",
    "2S": "South Asia",
    "3A": "Europe",
    "3B": "Balkan States",
    "3D": "Scandinavia",
    "3E": "Eastern Europe",
    "3L": "Baltic States",
    "3S": "Southern Europe",
    "3T": "Transcaucasus",
    "3W": "Western Europe",
    "4C": "Central America",
    "4L": "Latin America",
    "4N": "North America",
    "4R": "Caribbean",
    "4S": "South America",
    "5A": "Australia-New Zealand Region",
    "6A": "Arctic Ocean Area",
    "6D": "North Atlantic Area",
    "6E": "North Pacific Area",
    "6G": "South Atlantic Area",
    "6H": "South Pacific Ocean Area",
    "6I": "Indian Ocean Area",
    "6M": "Mediterranean Sea Area",
    "6P": "Persian Gulf Area",
    "7A": "Worldwide",
    "8A": "Antarctic Area",
}

# Source: 5 FAH-3 (State Dept RG59) "TRAFFIC ANALYSIS BY GEOGRAPHY AND SUBJECT"
# handbook, TL:TAGS-1, 6-28-74 (docs/rg59_state_dept_tags_74.pdf, Section 11
# "List of Geographic TAGS Alphabetically by Country or World Regions") --
# PERIOD-ACCURATE for this corpus's 1973-1979 date range (unlike COUNTRY_TAGS/
# REGION_TAGS above, which are the *current* 2024 State Dept reference).
# Transcribed directly from page images (OCR of this scan is too poor to trust).
# This is the PRIMARY geographic lookup -- see lookup_geographic_tag().
COUNTRY_TAGS_1974 = {
    "AC": "Antigua",
    "AF": "Afghanistan",
    "AG": "Algeria",
    "AL": "Albania",
    "AN": "Andorra",
    "AO": "Angola",
    "AQ": "American Samoa",
    "AR": "Argentina",
    "AS": "Australia",
    "AT": "Ashmore and Cartier Islands",
    "AU": "Austria",
    "AV": "Anguilla",
    "BA": "Bahrain",
    "BB": "Barbados",
    "BC": "Botswana",
    "BD": "Bermuda",
    "BE": "Belgium",
    "BF": "Bahamas",
    "BG": "Bangladesh",
    "BH": "Belize",
    "BL": "Bolivia",
    "BM": "Burma",
    "BP": "British Solomon Islands",
    "BR": "Brazil",
    "BT": "Bhutan",
    "BU": "Bulgaria",
    "BV": "Bouvet Island",
    "BW": "British West Indies",
    "BX": "Brunei",
    "BY": "Burundi",
    "CA": "Canada",
    "CB": "Cambodia (Khmer Republic)",
    "CD": "Chad",
    "CE": "Sri Lanka (Ceylon)",
    "CF": "Congo (Brazzaville)",
    "CG": "Zaire",
    "CH": "China (Mainland)",
    "CI": "Chile",
    "CJ": "Cayman Islands",
    "CK": "Cocos Island",
    "CL": "Line Islands",
    "CM": "Cameroon",
    "CN": "Comoro Islands",
    "CO": "Colombia",
    "CR": "Coral Sea Islands Territory",
    "CS": "Costa Rica",
    "CT": "Central African Republic",
    "CU": "Cuba",
    "CV": "Cape Verde Islands",
    "CW": "Cook Islands",
    "CY": "Cyprus",
    "CZ": "Czechoslovakia",
    "DA": "Denmark",
    "DM": "Dahomey",
    "DO": "Dominica",
    "DR": "Dominican Republic",
    "EC": "Ecuador",
    "EG": "Egypt",
    "EI": "Ireland",
    "EK": "Equatorial Guinea",
    "EQ": "Canton and Enderbury Islands",
    "ES": "El Salvador",
    "ET": "Ethiopia",
    "FA": "Falkland Islands",
    "FG": "French Guiana",
    "FI": "Finland",
    "FJ": "Fiji",
    "FO": "Faeroe Islands",
    "FP": "French Polynesia",
    "FR": "France",
    "FT": "French Territory of Afars and Issas",
    "FW": "French West Indies",
    "GA": "Gambia",
    "GB": "Gabon",
    "GE": "Germany (East)",
    "GH": "Ghana",
    "GI": "Gibraltar",
    "GJ": "Grenada",
    "GL": "Greenland",
    "GN": "Gilbert and Ellice Islands",
    "GP": "Guadeloupe",
    "GQ": "Guam",
    "GR": "Greece",
    "GT": "Guatemala",
    "GV": "Guinea",
    "GW": "Germany (West)",
    "GY": "Guyana",
    "GZ": "Gaza Strip",
    "HA": "Haiti",
    "HK": "Hong Kong",
    "HM": "Heard and McDonald Islands",
    "HO": "Honduras",
    "HU": "Hungary",
    "IC": "Iceland",
    "ID": "Indonesia",
    "IN": "India",
    "IO": "British Indian Ocean Territory",
    "IR": "Iran",
    "IS": "Israel",
    "IT": "Italy",
    "IV": "Ivory Coast",
    "IY": "Iraq-Saudi Arabia Neutral Zone",
    "IZ": "Iraq",
    "JA": "Japan",
    "JM": "Jamaica",
    "JN": "Jan Mayen",
    "JO": "Jordan",
    "JQ": "Johnston Atoll",
    "KE": "Kenya",
    "KN": "Korea (North)",
    "KS": "Korea (South)",
    "KT": "Christmas Island",
    "KU": "Kuwait",
    "LA": "Laos",
    "LE": "Lebanon",
    "LI": "Liberia",
    "LS": "Liechtenstein",
    "LT": "Lesotho",
    "LU": "Luxembourg",
    "LY": "Libya",
    "MA": "Madagascar (Malagasy Republic)",
    "MB": "Martinique",
    "MC": "Macao",
    "MG": "Mongolia",
    "MH": "Montserrat",
    "MI": "Malawi",
    "ML": "Mali",
    "MN": "Monaco",
    "MO": "Morocco",
    "MP": "Mauritius",
    "MQ": "Midway Islands",
    "MR": "Mauritania",
    "MT": "Malta",
    "MU": "Oman",
    "MV": "Maldives",
    "MX": "Mexico",
    "MY": "Malaysia",
    "MZ": "Mozambique",
    "NA": "Netherlands Antilles",
    "NC": "New Caledonia",
    "NE": "Niue",
    "NF": "Norfolk Island",
    "NG": "Niger",
    "NH": "New Hebrides",
    "NI": "Nigeria",
    "NL": "Netherlands",
    "NO": "Norway",
    "NP": "Nepal",
    "NR": "Nauru",
    "NS": "Surinam",
    "NU": "Nicaragua",
    "NZ": "New Zealand",
    "PA": "Paraguay",
    "PC": "Pitcairn Island",
    "PE": "Peru",
    "PF": "Paracel Islands",
    "PG": "Spratly Island",
    "PK": "Pakistan",
    "PL": "Poland",
    "PN": "Panama",
    "PO": "Portugal",
    "PP": "Papua New Guinea",
    "PQ": "Canal Zone",
    "PT": "Portuguese Timor",
    "PU": "Portuguese Guinea",
    "QA": "Qatar",
    "RE": "Reunion",
    "RH": "Rhodesia",
    "RO": "Romania",
    "RP": "Philippines",
    "RQ": "Puerto Rico",
    "RW": "Rwanda",
    "SA": "Saudi Arabia",
    "SB": "St. Pierre and Miquelon",
    "SC": "St. Christopher-Nevis",
    "SE": "Seychelles",
    "SF": "South Africa",
    "SG": "Senegal",
    "SH": "St. Helena",
    "SK": "Sikkim",
    "SL": "Sierra Leone",
    "SM": "San Marino",
    "SN": "Singapore",
    "SO": "Somalia",
    "SP": "Spain",
    "SQ": "Swan Islands",
    "SS": "Spanish Sahara",
    "ST": "St. Lucia",
    "SU": "Sudan",
    "SV": "Svalbard",
    "SW": "Sweden",
    "SY": "Syria",
    "SZ": "Switzerland",
    "TC": "United Arab Emirates (UAE)",
    "TD": "Trinidad and Tobago",
    "TH": "Thailand",
    "TN": "Tonga",
    "TO": "Togo",
    "TP": "Sao Tome and Principe",
    "TQ": "Trust Territory of the Pacific",
    "TS": "Tunisia",
    "TU": "Turkey",
    "TW": "China (Taiwan)",
    "TZ": "Tanzania",
    "UG": "Uganda",
    "UK": "United Kingdom",
    "UR": "Soviet Union",
    "US": "United States",
    "UV": "Upper Volta",
    "UY": "Uruguay",
    "VC": "St. Vincent",
    "VE": "Venezuela",
    "VI": "British Virgin Islands",
    "VN": "Viet-Nam (North)",
    "VQ": "Virgin Islands",
    "VS": "Viet-Nam (South)",
    "VT": "Vatican City",
    "WA": "South-West Africa",
    "WB": "West Berlin",
    "WQ": "Wake Island",
    "WS": "Western Samoa",
    "WZ": "Swaziland",
    "YE": "Yemen (San'a)",
    "YO": "Yugoslavia",
    "YQ": "Ryukyu Islands (South)",
    "YS": "Yemen (Aden)",
    "ZA": "Zambia",
}

# Source: same 1974 handbook, Section 11 "World Regions" subsection.
REGION_TAGS_1974 = {
    "XA": "Africa",
    "XB": "Asia",
    "XC": "Southeast Asia",
    "XD": "South Asia",
    "XE": "Far East",
    "XF": "Middle East",
    "XG": "Europe",
    "XH": "Eastern Europe",
    "XI": "North Africa",
    "XJ": "Africa South of the Sahara",
    "XK": "Central America",
    "XL": "Caribbean",
    "XM": "Latin America",
    "XN": "Atlantic Ocean Area",
    "XO": "Indian Ocean Area",
    "XP": "Pacific Ocean Area",
    "XQ": "Arctic Ocean Area",
    "XR": "South America",
    "XS": "North America",
    "XT": "Western Europe",
    "XU": "Australasia",
    "XV": "Antarctica",
    "XW": "East Africa",
    "XX": "Worldwide",
    "XY": "West Africa",
    "XZ": "Scandinavia",
}

# Appendix I: "All Subject TAGS in the [E/M/P/S/T] field are permanent." The FAQ
# does not enumerate these codes (see the on-line TAGS handbooks for details).
_WILDCARD_PERMANENT_PREFIXES = frozenset({"E", "M", "P", "S", "T"})

_WILDCARD_FIELD_NAMES = {
    "E": "Economic Affairs",
    "M": "Military and Defense Affairs",
    "P": "Political Affairs",
    "S": "Social Affairs",
    "T": "Technology and Science",
}


def classify_subject_tag(code: str) -> tuple[str, str | None]:
    """Classify a 4-letter Subject TAGS code per docs/faqs.txt Appendix I/II.

    Returns (status, title):
      status is one of "permanent", "temporary", "permanent-wildcard", "unknown".
      title is the Appendix title text, or None if not explicitly enumerated
      (wildcard-covered and unknown codes have no title in the FAQ).
    """
    code = code.strip().upper()

    if code in PERMANENT_SUBJECT_TAGS:
        _, title = PERMANENT_SUBJECT_TAGS[code]
        return "permanent", title

    if code in TEMPORARY_SUBJECT_TAGS:
        _, title = TEMPORARY_SUBJECT_TAGS[code]
        return "temporary", title

    if len(code) == 4 and code[0] in _WILDCARD_PERMANENT_PREFIXES:
        return "permanent-wildcard", None

    return "unknown", None


def lookup_organization_tag(code: str) -> str | None:
    """Look up a code in ORGANIZATION_TAGS (non-FAQ, research-derived).

    Returns the meaning string, or None if the code isn't in this mapping.
    """
    return ORGANIZATION_TAGS.get(code.strip().upper())


def lookup_geographic_tag(code: str) -> str | None:
    """Look up a code in the geographic TAGS mappings.

    Checks COUNTRY_TAGS_1974/REGION_TAGS_1974 (the period-accurate 1974
    handbook -- primary, since this corpus is 1973-1979) first, then falls
    back to the current COUNTRY_TAGS/REGION_TAGS (5 FAH-3 H-414/H-416) for
    codes not covered by the 1974 handbook (e.g. entities that gained
    independence after June 1974, like Angola or Mozambique).

    Returns the country/region name, or None if not found in either. Absence
    does NOT mean the code is invalid -- see module docstring for why a code
    can legitimately be missing from both (e.g. a later handbook revision
    added it, or OCR/transcription noise in the source cable).
    """
    code = code.strip().upper()
    return (
        COUNTRY_TAGS_1974.get(code)
        or REGION_TAGS_1974.get(code)
        or COUNTRY_TAGS.get(code)
        or REGION_TAGS.get(code)
    )
